name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node: [16, 18, 20]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      # - name: Setup Node | ${{ matrix.node }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # node-version: ${{ matrix.node }}
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run test

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: brsantos197/rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }},brsantos197/rocketseat-ci-api:latest

      # - name: Build docker image
      #   run: docker build -t brsantos197/rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }} .

      # - name: Push image
      #   run: docker push brsantos197/rocketseat-ci-api:${{ steps.generate_tag.outputs.sha }}
